# Config file for automatic testing at travis-ci.org

sudo: required

language: python

services:
  - docker

before_install:
  - docker pull usdaarsnwrc/smrf:latest
  - docker build --build-arg REQUIREMENTS=_dev -t usdaarsnwrc/awsm .

script:
  docker run -it usdaarsnwrc/awsm test
